name: Node Continuous Integration

on:
    push: 
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs: 
    build: 
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                node-version: 18
                cache: 'yarn'
            - run: yarn install --frozen-lockfile
            - run: yarn test
            - run: yarn run build